Repository AY2425S2-CS2113-W11-2/tp, pull requests merged in 2025-03, with the labels that each got.

#21 Nicholas expenses1.0
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/expense/Expense.java
  src/main/java/seedu/duke/expense/ExpenseCommandParser.java
  src/main/java/seedu/duke/expense/ExpenseManager.java
  src/main/java/seedu/duke/expense/commands/AddCommand.java
  src/main/java/seedu/duke/expense/commands/DeleteCommand.java
  src/main/java/seedu/duke/expense/commands/ExpenseCommand.java
  src/main/java/seedu/duke/expense/commands/ListAllCommand.java
  src/main/java/seedu/duke/expense/commands/ListExpenseCommand.java
  src/main/java/seedu/duke/income/Income.java
  src/main/java/seedu/duke/income/IncomeCommandParser.java
  src/main/java/seedu/duke/income/IncomeManager.java
  src/main/java/seedu/duke/income/commands/AddCommand.java
  src/main/java/seedu/duke/income/commands/DeleteCommand.java
  src/main/java/seedu/duke/income/commands/IncomeCommand.java
  src/main/java/seedu/duke/income/commands/ListIncomeCommand.java
Labels: priority.High, type.Story

#29 Refactor expense and income packages
  src/main/java/expense/Expense.java
  src/main/java/expense/ExpenseCommandParser.java
  src/main/java/expense/ExpenseManager.java
  src/main/java/expense/commands/AddCommand.java
  src/main/java/expense/commands/DeleteCommand.java
  src/main/java/expense/commands/ExpenseCommand.java
  src/main/java/expense/commands/ListAllCommand.java
  src/main/java/expense/commands/ListExpenseCommand.java
  src/main/java/income/Income.java
  src/main/java/income/IncomeCommandParser.java
  src/main/java/income/IncomeManager.java
  src/main/java/income/commands/AddCommand.java
  src/main/java/income/commands/DeleteCommand.java
  src/main/java/income/commands/IncomeCommand.java
  src/main/java/income/commands/ListIncomeCommand.java
Labels: priority.High

#36 Integrate to main
  src/main/java/cashflow/model/FinanceData.java
  src/main/java/cashflow/ui/UI.java
  src/main/java/expense_income/expense/ExpenseCommandParser.java
  src/main/java/expense_income/income/IncomeCommandParser.java
Labels: priority.High

#57 Implemented the loan commands into UI
  src/main/java/cashflow/ui/UI.java
  src/main/java/loanbook/loanbook/LoanList.java
  src/main/java/loanbook/loanbook/commands/AddAdvancedLoanCommand.java
  src/main/java/loanbook/loanbook/commands/AddSimpleBulletLoanCommand.java
  src/main/java/loanbook/loanbook/commands/DeleteLoanCommand.java
  src/main/java/loanbook/loanbook/commands/InvalidCommand.java
  src/main/java/loanbook/loanbook/commands/ListCommand.java
  src/main/java/loanbook/loanbook/commands/LoanCommand.java
  src/main/java/loanbook/loanbook/commands/ShowDetailCommand.java
  src/main/java/loanbook/loanbook/interest/CommonPeriods.java
  src/main/java/loanbook/loanbook/interest/Interest.java
  src/main/java/loanbook/loanbook/interest/InterestApplier.java
  src/main/java/loanbook/loanbook/interest/InterestType.java
  src/main/java/loanbook/loanbook/loan/AdvancedBulletLoan.java
  src/main/java/loanbook/loanbook/loan/AdvancedLoan.java
  src/main/java/loanbook/loanbook/loan/DateUndefinedException.java
  src/main/java/loanbook/loanbook/loan/Direction.java
  src/main/java/loanbook/loanbook/loan/Loan.java
  src/main/java/loanbook/loanbook/loan/SimpleBulletLoan.java
  src/main/java/loanbook/loanbook/parsers/InterestParser.java
  src/main/java/loanbook/loanbook/parsers/LoanCommandParser.java
  src/main/java/loanbook/loanbook/save/LoanSaveManager.java
  src/main/java/lonebook/loanbook/commands/AddAdvancedLoanCommand.java
  src/main/java/lonebook/loanbook/commands/AddSimpleBulletLoanCommand.java
  src/main/java/lonebook/loanbook/commands/LoanCommand.java
  src/main/java/lonebook/loanbook/commands/invalidcommands/InvalidLoanCommand.java
  src/main/java/lonebook/loanbook/interest/InterestApplier.java
  src/main/java/lonebook/loanbook/loan/Direction.java
  src/main/java/utils/datetime/DateParser.java
  src/main/java/utils/people/PeopleList.java
  src/test/java/loantests/LoanListTest.java
Labels: type.Story

#59 Add assertions for Expense and Income classes
  src/main/java/expense_income/expense/Expense.java
  src/main/java/expense_income/expense/commands/AddCommand.java
  src/main/java/expense_income/expense/commands/DeleteCommand.java
  src/main/java/expense_income/expense/commands/ListExpenseCommand.java
  src/main/java/expense_income/income/Income.java
  src/main/java/expense_income/income/commands/AddCommand.java
  src/main/java/expense_income/income/commands/DeleteCommand.java
  src/main/java/expense_income/income/commands/ListIncomeCommand.java
Labels: priority.High

#61 Edit inputs
  src/main/java/expense_income/expense/Expense.java
  src/main/java/expense_income/expense/ExpenseCommandParser.java
  src/main/java/expense_income/expense/ExpenseManager.java
  src/main/java/expense_income/expense/commands/AddExpenseCommand.java
  src/main/java/expense_income/expense/commands/DeleteExpenseCommand.java
  src/main/java/expense_income/expense/commands/EditExpenseCommand.java
  src/main/java/expense_income/income/Income.java
  src/main/java/expense_income/income/IncomeCommandParser.java
  src/main/java/expense_income/income/IncomeManager.java
  src/main/java/expense_income/income/commands/AddIncomeCommand.java
  src/main/java/expense_income/income/commands/DeleteIncomeCommand.java
  src/main/java/expense_income/income/commands/EditIncomeCommand.java
Labels: priority.High

#62 Date inputs
  src/main/java/expense_income/expense/Expense.java
  src/main/java/expense_income/expense/ExpenseCommandParser.java
  src/main/java/expense_income/expense/ExpenseManager.java
  src/main/java/expense_income/expense/commands/AddExpenseCommand.java
  src/main/java/expense_income/expense/commands/EditExpenseCommand.java
  src/main/java/expense_income/expense/commands/SortExpenseCommand.java
  src/main/java/expense_income/income/Income.java
  src/main/java/expense_income/income/IncomeCommandParser.java
  src/main/java/expense_income/income/IncomeManager.java
  src/main/java/expense_income/income/commands/AddIncomeCommand.java
  src/main/java/expense_income/income/commands/EditIncomeCommand.java
  src/main/java/expense_income/income/commands/SortIncomeCommand.java
Labels: priority.High

#63 Improve unit testing code
  src/test/java/expensetest/ExpenseManagerTest.java
  src/test/java/incometest/IncomeManagerTest.java
Labels: priority.High

#64 Add category
  src/main/java/expense_income/expense/Expense.java
  src/main/java/expense_income/expense/ExpenseCommandParser.java
  src/main/java/expense_income/expense/ExpenseManager.java
  src/main/java/expense_income/expense/commands/AddExpenseCommand.java
  src/main/java/expense_income/expense/commands/EditExpenseCommand.java
  src/main/java/expense_income/income/Income.java
  src/main/java/expense_income/income/IncomeCommandParser.java
  src/main/java/expense_income/income/IncomeManager.java
  src/main/java/expense_income/income/commands/AddIncomeCommand.java
  src/main/java/expense_income/income/commands/EditIncomeCommand.java
Labels: priority.High

#69 Implement logging to expense and income manager
  src/main/java/expense_income/expense/ExpenseManager.java
  src/main/java/expense_income/income/IncomeManager.java
Labels: priority.High

#70 List category
  src/main/java/expense_income/expense/ExpenseCommandParser.java
  src/main/java/expense_income/expense/ExpenseManager.java
  src/main/java/expense_income/expense/commands/ListCategoryExpenseCommand.java
  src/main/java/expense_income/income/IncomeCommandParser.java
  src/main/java/expense_income/income/IncomeManager.java
  src/main/java/expense_income/income/commands/ListCategoryIncomeCommand.java
Labels: priority.Medium

#72 Implemented set loan commands and improved the UI
  src/main/java/cashflow/ui/UI.java
  src/main/java/loanbook/loanbook/LoanList.java
  src/main/java/loanbook/loanbook/commands/InvalidCommand.java
  src/main/java/loanbook/loanbook/commands/addcommands/AddAdvancedLoanCommand.java
  src/main/java/loanbook/loanbook/commands/addcommands/AddSimpleBulletLoanCommand.java
  src/main/java/loanbook/loanbook/commands/addcommands/AddTagCommand.java
  src/main/java/loanbook/loanbook/commands/setcommands/SetCommand.java
  src/main/java/loanbook/loanbook/commands/setcommands/SetDescriptionCommand.java
  src/main/java/loanbook/loanbook/commands/setcommands/SetInterestCommand.java
  src/main/java/loanbook/loanbook/commands/setcommands/SetPrincipalCommand.java
  src/main/java/loanbook/loanbook/commands/setcommands/SetReturnDateCommand.java
  src/main/java/loanbook/loanbook/commands/setcommands/SetReturnStatusCommand.java
  src/main/java/loanbook/loanbook/commands/setcommands/SetStartDateCommand.java
  src/main/java/loanbook/loanbook/loan/AdvancedLoan.java
  src/main/java/loanbook/loanbook/loan/Loan.java
  src/main/java/loanbook/loanbook/parsers/InterestParser.java
  src/main/java/loanbook/loanbook/parsers/LoanCommandParser.java
  src/main/java/utils/datetime/DateParser.java
  src/main/java/utils/money/Money.java
  src/main/java/utils/money/MoneyParser.java
  src/test/java/loantests/LoanListTest.java
  src/test/java/parsertests/DateParserTest.java
Labels: priority.High, type.Story

#74 Debug unit test code
  src/test/java/expensetest/ExpenseManagerTest.java
  src/test/java/incometest/IncomeManagerTest.java
Labels: type.bug

#75 Refactor main and test code to comply with checkstyle
  build.gradle
  docs/DeveloperGuide.md
  src/main/java/budget_saving/budget/Budget.java
  src/main/java/budget_saving/budget/BudgetList.java
  src/main/java/cashflow/model/FinanceData.java
  src/main/java/cashflow/ui/UI.java
  src/main/java/expenseincome/expense/Expense.java
  src/main/java/expenseincome/expense/ExpenseCommandParser.java
  src/main/java/expenseincome/expense/ExpenseManager.java
  src/main/java/expenseincome/expense/commands/AddExpenseCommand.java
  src/main/java/expenseincome/expense/commands/DeleteExpenseCommand.java
  src/main/java/expenseincome/expense/commands/EditExpenseCommand.java
  src/main/java/expenseincome/expense/commands/ExpenseCommand.java
  src/main/java/expenseincome/expense/commands/ListAllCommand.java
  src/main/java/expenseincome/expense/commands/ListCategoryExpenseCommand.java
  src/main/java/expenseincome/expense/commands/ListExpenseCommand.java
  src/main/java/expenseincome/expense/commands/SortExpenseCommand.java
  src/main/java/expenseincome/income/Income.java
  src/main/java/expenseincome/income/IncomeCommandParser.java
  src/main/java/expenseincome/income/IncomeManager.java
  src/main/java/expenseincome/income/commands/AddIncomeCommand.java
  src/main/java/expenseincome/income/commands/DeleteIncomeCommand.java
  src/main/java/expenseincome/income/commands/EditIncomeCommand.java
  src/main/java/expenseincome/income/commands/IncomeCommand.java
  src/main/java/expenseincome/income/commands/ListCategoryIncomeCommand.java
  src/main/java/expenseincome/income/commands/ListIncomeCommand.java
  src/main/java/expenseincome/income/commands/SortIncomeCommand.java
  src/test/java/expensetest/ExpenseCommandParserTest.java
  src/test/java/expensetest/ExpenseCommandTestSuite.java
  src/test/java/expensetest/ExpenseManagerTest.java
  src/test/java/incometest/IncomeCommandParserTest.java
  src/test/java/incometest/IncomeCommandTestSuite.java
  src/test/java/incometest/IncomeManagerTest.java
Labels: priority.High, severity.High, type.bug

#76 Add assertions on gradle
  build.gradle
Labels: priority.High

#77 Enhance category
  src/main/java/expenseincome/expense/ExpenseCommandParser.java
  src/main/java/expenseincome/expense/ExpenseManager.java
  src/main/java/expenseincome/expense/commands/BottomCategoryExpenseCommand.java
  src/main/java/expenseincome/expense/commands/HelpExpenseCommand.java
  src/main/java/expenseincome/expense/commands/TopCategoryExpenseCommand.java
  src/main/java/expenseincome/income/IncomeCommandParser.java
  src/main/java/expenseincome/income/IncomeManager.java
  src/main/java/expenseincome/income/commands/BottomCategoryIncomeCommand.java
  src/main/java/expenseincome/income/commands/HelpIncomeCommand.java
  src/main/java/expenseincome/income/commands/TopCategoryIncomeCommand.java
Labels: priority.Medium, type.Enhancement

#78 Corrected code style.
  src/main/java/budgetsaving/budget/Budget.java
  src/main/java/budgetsaving/budget/BudgetException.java
  src/main/java/budgetsaving/budget/BudgetList.java
  src/main/java/budgetsaving/budget/command/AddToBudgetCommand.java
  src/main/java/budgetsaving/budget/command/BudgetGeneralCommand.java
  src/main/java/budgetsaving/budget/command/CheckBudgetCommand.java
  src/main/java/budgetsaving/budget/command/DeductFromBudgetCommand.java
  src/main/java/budgetsaving/budget/command/ListBudgetCommand.java
  src/main/java/budgetsaving/budget/command/ModifyBudgetCommand.java
  src/main/java/budgetsaving/budget/command/SetBudgetCommand.java
  src/main/java/budgetsaving/budget/utils/BudgetAlert.java
  src/main/java/budgetsaving/budget/utils/BudgetAttributes.java
  src/main/java/budgetsaving/budget/utils/BudgetParser.java
  src/main/java/budgetsaving/budget/utils/BudgetTextColour.java
  src/main/java/budgetsaving/saving/Saving.java
  src/main/java/budgetsaving/saving/SavingException.java
  src/main/java/budgetsaving/saving/SavingList.java
  src/main/java/budgetsaving/saving/command/CheckGoalCommand.java
  src/main/java/budgetsaving/saving/command/ContributeGoalCommand.java
  src/main/java/budgetsaving/saving/command/SavingGeneralCommand.java
  src/main/java/budgetsaving/saving/command/SetGoalCommand.java
  src/main/java/cashflow/model/interfaces/BudgetManager.java
  src/main/java/cashflow/ui/UI.java
  src/test/java/budgettest/BudgetListTest.java
  src/test/java/budgettest/BudgetTest.java
Labels: priority.Medium

#81 Improve junit
  src/test/java/expensetest/ExpenseCommandTestSuite.java
  src/test/java/incometest/IncomeCommandTestSuite.java
Labels: priority.High
