Repository AY2425S2-CS2113-W11-2/tp, pull requests merged in 2025-04, with the labels that each got.

#84 Add ug dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddExpenseSequence.puml
  docs/diagrams/ExpenseIncomeManager.puml
  docs/img.png
  docs/img_1.png
  docs/img_2.png
Labels: priority.High

#87 Add PPP based on specifications
  docs/img.png
  docs/team/nicholascxh.md
Labels: priority.High

#89 Refactor code
  src/main/java/cashflow/CashFlowManager.java
  src/main/java/cashflow/model/FinanceData.java
  src/main/java/cashflow/ui/UI.java
  src/main/java/expenseincome/expense/HandleExpenseCommand.java
  src/main/java/expenseincome/income/HandleIncomeCommand.java
Labels: priority.High

#93 Integration
  src/main/java/cashflow/analytics/AnalyticsManager.java
  src/main/java/cashflow/model/interfaces/ExpenseDataManager.java
  src/main/java/cashflow/model/interfaces/IncomeDataManager.java
  src/main/java/expenseincome/expense/Expense.java
  src/main/java/expenseincome/expense/ExpenseManager.java
  src/main/java/expenseincome/income/Income.java
  src/main/java/expenseincome/income/IncomeManager.java
Labels: priority.High

#96 Update dgandug
  docs/DeveloperGuide.md
  docs/diagrams/AddExpenseSequence.puml
  docs/diagrams/ExpenseIncomeManager.puml
  docs/img.png
  docs/img_3.png
Labels: priority.High

#97 Refactor for more OOP with analytic.command
  src/main/java/cashflow/CashFlowManager.java
  src/main/java/cashflow/analytics/AnalyticsManager.java
  src/main/java/cashflow/analytics/command/AnalyticGeneralCommand.java
  src/main/java/cashflow/analytics/command/CommandHandler.java
  src/main/java/cashflow/analytics/command/OverviewCommand.java
  src/main/java/cashflow/analytics/parser/AnalyticCommandParser.java
  src/main/java/cashflow/dummy/DummyExpense.class
  src/main/java/cashflow/dummy/DummyExpense.java
  src/main/java/cashflow/dummy/DummyLoan.class
  src/main/java/cashflow/dummy/DummyLoan.java
  src/main/java/cashflow/dummy/DummySavings.class
  src/main/java/cashflow/dummy/DummySavings.java
  src/main/java/cashflow/model/FinanceData.java
  src/main/java/cashflow/model/interfaces/ExpenseIncomeManager.class
  src/main/java/cashflow/model/interfaces/LoanDebtManager.class
  src/main/java/cashflow/model/interfaces/LoanDebtManager.java
  src/main/java/cashflow/ui/SetUp.java
  src/main/java/cashflow/ui/UI.java
  src/main/java/cashflow/ui/command/Command.java
  src/main/java/cashflow/ui/command/HelpCommand.java
  src/main/java/cashflow/ui/command/OverviewCommand.java
  src/main/java/cashflow/ui/command/SetUpCommand.java
  src/main/java/loanbook/loan/AdvancedLoan.java
  src/main/java/loanbook/loan/SimpleBulletLoan.java
Labels: priority.High

#100 Update expense manager to use budgetmanager from financedata
  docs/team/nicholascxh.md
  src/main/java/cashflow/model/FinanceData.java
  src/main/java/expenseincome/expense/ExpenseManager.java
Labels: priority.High

#106 Refactor code again
  docs/UserGuide.md
  src/main/java/cashflow/ui/UI.java
  src/main/java/expenseincome/expense/ExpenseManager.java
  src/main/java/expenseincome/expense/HandleExpenseCommand.java
  src/main/java/expenseincome/income/HandleIncomeCommand.java
  src/main/java/expenseincome/income/IncomeManager.java
  src/test/java/expensetest/ExpenseManagerTest.java
  src/test/java/incometest/IncomeManagerTest.java
Labels: priority.High

#163 Fix bugs 1
  src/main/java/cashflow/model/interfaces/ExpenseDataManager.java
  src/main/java/expenseincome/expense/ExpenseCommandParser.java
  src/main/java/expenseincome/expense/ExpenseManager.java
  src/main/java/expenseincome/expense/ExpenseParserResult.java
  src/main/java/expenseincome/expense/HandleExpenseCommand.java
  src/main/java/expenseincome/expense/commands/HelpExpenseCommand.java
  src/main/java/expenseincome/income/HandleIncomeCommand.java
  src/main/java/expenseincome/income/IncomeCommandParser.java
  src/main/java/expenseincome/income/IncomeManager.java
  src/main/java/expenseincome/income/IncomeParserResult.java
  src/main/java/expenseincome/income/commands/HelpIncomeCommand.java
Labels: priority.High

#164 Fix bugs 2
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/diagrams/AddExpenseSequence.puml
  docs/diagrams/EditIncomeSequence.puml
  docs/diagrams/ExpenseIncomeManager.puml
  docs/diagrams/ExpenseManager.puml
  docs/diagrams/IncomeManager.puml
  docs/img_4.png
  docs/img_5.png
  docs/img_6.png
  docs/img_7.png
  docs/img_8.png
  docs/team/nicholascxh.md
  logs/expense.log
  logs/expense.log.lck
  logs/income.log
  logs/income.log.lck
  src/main/java/cashflow/model/interfaces/ExpenseDataManager.java
  src/main/java/cashflow/model/interfaces/IncomeDataManager.java
  src/main/java/expenseincome/expense/ExpenseCommandParser.java
  src/main/java/expenseincome/expense/ExpenseManager.java
  src/main/java/expenseincome/expense/commands/HelpExpenseCommand.java
  src/main/java/expenseincome/income/IncomeCommandParser.java
  src/main/java/expenseincome/income/IncomeManager.java
  src/main/java/expenseincome/income/commands/HelpIncomeCommand.java
  src/test/java/expensetest/ExpenseCommandParserTest.java
  src/test/java/expensetest/ExpenseCommandTestSuite.java
  src/test/java/incometest/IncomeCommandParserTest.java
Labels: priority.High, type.bug

#165 Added defensive code for saving, and enhanced IOHandler
  src/main/java/budgetsaving/budget/Budget.java
  src/main/java/budgetsaving/budget/BudgetList.java
  src/main/java/budgetsaving/budget/command/AddToBudgetCommand.java
  src/main/java/budgetsaving/budget/command/BudgetGeneralCommand.java
  src/main/java/budgetsaving/budget/exceptions/BudgetException.java
  src/main/java/budgetsaving/budget/exceptions/BudgetRuntimeException.java
  src/main/java/budgetsaving/budget/utils/BudgetAlert.java
  src/main/java/budgetsaving/budget/utils/BudgetAttributes.java
  src/main/java/budgetsaving/budget/utils/BudgetParser.java
  src/main/java/budgetsaving/saving/Saving.java
  src/main/java/budgetsaving/saving/SavingContribution.java
  src/main/java/budgetsaving/saving/SavingException.java
  src/main/java/budgetsaving/saving/SavingList.java
  src/main/java/budgetsaving/saving/command/CheckSavingCommand.java
  src/main/java/budgetsaving/saving/command/ContributeGoalCommand.java
  src/main/java/budgetsaving/saving/command/DeleteContributionCommand.java
  src/main/java/budgetsaving/saving/command/DeleteSavingCommand.java
  src/main/java/budgetsaving/saving/command/ListSavingsCommand.java
  src/main/java/budgetsaving/saving/command/SavingGeneralCommand.java
  src/main/java/budgetsaving/saving/command/SavingHelpCommand.java
  src/main/java/budgetsaving/saving/command/SetSavingCommand.java
  src/main/java/budgetsaving/saving/exceptions/SavingAttributeException.java
  src/main/java/budgetsaving/saving/exceptions/SavingException.java
  src/main/java/budgetsaving/saving/exceptions/SavingParserException.java
  src/main/java/budgetsaving/saving/exceptions/SavingRuntimeException.java
  src/main/java/budgetsaving/saving/utils/SavingAttributes.java
  src/main/java/budgetsaving/saving/utils/SavingParser.java
  src/main/java/cashflow/model/interfaces/BudgetManager.java
  src/main/java/cashflow/model/interfaces/SavingManager.java
  src/main/java/utils/io/IOHandler.java
  src/main/java/utils/textcolour/TextColour.java
  src/test/java/savingtest/SavingModuleTest.java
Labels: priority.Medium

#166 Fix bugs 3
  docs/DeveloperGuide.md
  logs/income.log.lck
  src/main/java/expenseincome/expense/Expense.java
  src/main/java/expenseincome/expense/ExpenseCommandParser.java
  src/main/java/expenseincome/expense/ExpenseManager.java
  src/main/java/expenseincome/expense/ExpenseParserResult.java
  src/main/java/expenseincome/expense/HandleExpenseCommand.java
  src/main/java/expenseincome/expense/commands/AddExpenseCommand.java
  src/main/java/expenseincome/expense/commands/BottomCategoryExpenseCommand.java
  src/main/java/expenseincome/expense/commands/DeleteExpenseCommand.java
  src/main/java/expenseincome/expense/commands/EditExpenseCommand.java
  src/main/java/expenseincome/expense/commands/ExpenseCommand.java
  src/main/java/expenseincome/expense/commands/HelpExpenseCommand.java
  src/main/java/expenseincome/expense/commands/ListCategoryExpenseCommand.java
  src/main/java/expenseincome/expense/commands/ListExpenseCommand.java
  src/main/java/expenseincome/expense/commands/SortExpenseCommand.java
  src/main/java/expenseincome/expense/commands/TopCategoryExpenseCommand.java
  src/main/java/expenseincome/expense/exceptions/ExpenseException.java
  src/main/java/expenseincome/income/HandleIncomeCommand.java
  src/main/java/expenseincome/income/Income.java
  src/main/java/expenseincome/income/IncomeCommandParser.java
  src/main/java/expenseincome/income/IncomeManager.java
  src/main/java/expenseincome/income/IncomeParserResult.java
  src/main/java/expenseincome/income/commands/AddIncomeCommand.java
  src/main/java/expenseincome/income/commands/BottomCategoryIncomeCommand.java
  src/main/java/expenseincome/income/commands/DeleteIncomeCommand.java
  src/main/java/expenseincome/income/commands/EditIncomeCommand.java
  src/main/java/expenseincome/income/commands/HelpIncomeCommand.java
  src/main/java/expenseincome/income/commands/IncomeCommand.java
  src/main/java/expenseincome/income/commands/ListCategoryIncomeCommand.java
  src/main/java/expenseincome/income/commands/ListIncomeCommand.java
  src/main/java/expenseincome/income/commands/SortIncomeCommand.java
  src/main/java/expenseincome/income/commands/TopCategoryIncomeCommand.java
  src/main/java/expenseincome/income/exceptions/IncomeException.java
Labels: priority.High, type.Enhancement

#168 Fix issue with budget expense integration
  logs/income.log
  logs/income.log.lck
  src/main/java/budgetsaving/budget/Budget.java
  src/main/java/budgetsaving/budget/BudgetList.java
  src/test/java/budgettest/BudgetListTest.java
  src/test/java/budgettest/BudgetTest.java
  src/test/java/savingtest/SavingModuleTest.java
Labels: priority.High, type.bug

#170 Fix bugs 4
  README.md
  logs/income.log
  logs/income.log.lck
Labels: priority.High

#171 Completed budget expense integration
  docs/UserGuide.md
  logs/income.log
  src/main/java/budgetsaving/budget/BudgetList.java
  src/main/java/budgetsaving/budget/command/BudgetGeneralCommand.java
  src/main/java/budgetsaving/saving/command/SavingGeneralCommand.java
  src/main/java/utils/io/IOHandler.java
Labels: priority.High

#173 Fix bugs 5
  docs/DeveloperGuide.md
  docs/UserGuide.md
  logs/income.log
  logs/income.log.lck
  src/main/java/expenseincome/expense/ExpenseManager.java
Labels: priority.High, type.bug

#174 Updated DG
  docs/BudgetSavingSequence.png
  docs/BugdetExceptions.png
  docs/DeductBudgetFromExpense.png
  docs/DeveloperGuide.md
  docs/diagrams/BudgetManager.puml
  docs/diagrams/BudgetSavingSequence.puml
  docs/diagrams/BugdetExceptions.puml
  docs/diagrams/DeductBudgetFromExpense.puml
  docs/team/BudgetManager.png
  src/main/java/budgetsaving/budget/exceptions/BudgetNullCommandException.java
  src/main/java/budgetsaving/saving/command/SavingGeneralCommand.java
  src/main/java/budgetsaving/saving/command/SavingHelpCommand.java
Labels: priority.Medium, type.Task

#176 Fix bugs 6
  docs/AboutUs.md
  docs/UserGuide.md
Labels: priority.High, type.bug

#179 Fix bugs 7
  logs/analytics.log
  logs/analytics.log.lck
  logs/cashflow.log
  logs/cashflow.log.lck
  logs/expense.log
  src/main/java/expenseincome/expense/ExpenseManager.java
  src/main/java/expenseincome/income/IncomeManager.java
Labels: priority.High

#180 Fixed check style for budget and saving
  logs/analytics.log
  logs/cashflow.log
  logs/expense.log
  src/main/java/budgetsaving/budget/Budget.java
  src/main/java/budgetsaving/budget/BudgetList.java
  src/main/java/budgetsaving/budget/utils/BudgetAttributes.java
  src/main/java/budgetsaving/saving/SavingList.java
  src/main/java/budgetsaving/saving/command/DeleteContributionCommand.java
  src/main/java/budgetsaving/saving/command/DeleteSavingCommand.java
  src/main/java/budgetsaving/saving/command/SavingGeneralCommand.java
  src/main/java/budgetsaving/saving/command/SetSavingCommand.java
  src/main/java/budgetsaving/saving/utils/SavingAttributes.java
  src/main/java/budgetsaving/saving/utils/SavingParser.java
Labels: severity.VeryLow, priority.Low

#182 Fix bugs 8
  data/expense.dat
  data/income.dat
  logs/analytics.log
  logs/expense.log
  logs/income.log
  src/main/java/cashflow/model/interfaces/BudgetManager.java
  src/main/java/cashflow/model/storage/DummyStorage.java
  src/main/java/expenseincome/expense/ExpenseManager.java
  src/test/java/cashflow/AnalyticManagerTest.java
  src/test/java/cashflow/stub/StubExpenseManager.java
  src/test/java/cashflow/stub/StubIncomeManager.java
  src/test/java/expensetest/ExpenseCommandTestSuite.java
  src/test/java/expensetest/ExpenseHandleTest.java
  src/test/java/expensetest/ExpenseManagerTest.java
  src/test/java/incometest/IncomeCommandTestSuite.java
  src/test/java/incometest/IncomeHandleTest.java
  src/test/java/incometest/IncomeManagerTest.java
Labels: priority.High

#188 Fix ppp
  docs/team/nicholascxh.md
  src/main/java/expenseincome/expense/ExpenseManager.java
Labels: priority.High

#189 Fix bugs 9
  docs/AboutUs.md
  docs/georgesj1869.md
  docs/hudou0420.md
  docs/nicholascxh.md
  src/test/java/expensetest/ExpenseCommandParserTest.java
  src/test/java/incometest/IncomeCommandParserTest.java
Labels: priority.High

#191 Update PPP
  docs/nicholascxh.md
Labels: priority.High

#192 Old Commits
  logs/analytics.log
  logs/cashflow.log
  logs/expense.log
  logs/income.log
Labels: priority.High

#193 Fix bugs 10
  docs/nicholascxh.md
  src/test/java/incometest/IncomeCommandParserTest.java
Labels: priority.High

#194 Update PPP
  docs/nicholascxh.md
Labels: priority.High

#196 Update PPP
  docs/nicholascxh.md
Labels: priority.High

#197 Update PPP
  docs/nicholascxh.md
Labels: priority.High

#200 Integrate delete with budget which checks and output budget left
  data/budget.dat
  data/income.dat
  logs/analytics.log
  logs/cashflow.log
  logs/expense.log
  logs/income.log
  src/main/java/budgetsaving/budget/Budget.java
  src/main/java/budgetsaving/budget/BudgetList.java
  src/main/java/cashflow/model/interfaces/BudgetManager.java
  src/main/java/expenseincome/expense/ExpenseManager.java
Labels: priority.High

#204 Fixed bugs
  data/budget.dat
  data/saving.dat
  docs/DeveloperGuide.md
  docs/UserGuide.md
  logs/analytics.log
  logs/cashflow.log
  logs/expense.log
  logs/income.log
  save/loanManager/defaultUser_loans.txt
  save/loans/Test Two_loans.txt
  save/loans/Test_Save_loans.txt
  save/loans/defaultUser_loans.txt
  save/people/Miao_contacts.txt
  save/people/Test Two_contacts.txt
  save/people/Test_Save_contacts.txt
  save/people/defaultUser_contacts.txt
  src/main/java/budgetsaving/budget/Budget.java
  src/main/java/budgetsaving/budget/BudgetList.java
  src/main/java/budgetsaving/budget/utils/BudgetParser.java
  src/main/java/budgetsaving/saving/Saving.java
  src/test/java/budgettest/BudgetListTest.java
  src/test/java/budgettest/BudgetStorageDummy.java
Labels: priority.Medium, severity.High, type.bug

#207 Update dg ug
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddExpenseSequence.puml
  docs/diagrams/EditIncomeSequence.puml
  docs/diagrams/ExpenseManager.puml
  docs/diagrams/IncomeManager.puml
  docs/img_10.png
  docs/img_11.png
  docs/img_12.png
  docs/img_13.png
  docs/img_9.png
Labels: priority.High

#212 Update DG
  docs/DeveloperGuide.md
Labels: priority.High
